import assert from 'node:assert/strict';
import {terrainSight} from '../outputs/zerozone-haritalar/terrain-model.js';
const data={cols:101,rows:101,widthMeters:1000,heightMeters:1000,values:Array(10201).fill(0)};
const origin={x:.25,y:.5};
const flat=terrainSight(data,origin,{radius:700,size:61});
assert.equal(flat.visible,flat.total,'flat ground remains visible');
for(let y=0;y<101;y++)data.values[y*101+50]=80;
const ridge=terrainSight(data,origin,{radius:700,size:61});
const at=(r,x,y)=>r.cells[Math.floor((y-r.bounds.top)/(r.bounds.bottom-r.bounds.top)*r.size)*r.size+Math.floor((x-r.bounds.left)/(r.bounds.right-r.bounds.left)*r.size)];
assert.equal(at(ridge,.4,.5),1,'ground before ridge visible');
assert.equal(at(ridge,.75,.5),2,'ground behind ridge blocked');
assert.ok(ridge.visible<flat.visible);
assert.ok(terrainSight(data,origin,{radius:700,eye:100,size:61}).visible>ridge.visible,'raising eye reveals more ground');
const corner=terrainSight(data,{x:0,y:0},{radius:50,size:31});
assert.equal(corner.bounds.left,0);assert.equal(corner.bounds.top,0);assert.ok(corner.total>0);
assert.throws(()=>terrainSight(data,origin,{radius:Infinity}));
assert.throws(()=>terrainSight(data,origin,{eye:-1}));
assert.throws(()=>terrainSight(data,{x:2,y:0}));
console.log('Sight: flat plane, ridge occlusion, eye height, bounds and invalid inputs PASS');
